package view;

import javax.swing.JOptionPane;

public class FrmEmitirCupom extends javax.swing.JFrame {

    public FrmEmitirCupom() {
        initComponents();

    }

    public void preencherCampos(FrmHistorico telaHistorico, String cod, String data, String horaEntrada, String horaSaida, String desconto, String veiculo, String funcionario, String valor) {
        txtCodigo.setText("  " + cod);
        txtData.setText(data);
        txtHoraEntrada.setText(horaEntrada);
        txtHoraSaida.setText(horaSaida);
        txtVeiculo.setText(veiculo);
        txtDesconto.setText(desconto);
        txtValor.setText(valor);
        txtFuncionario.setText(funcionario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTelaHistorico = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        txtValor = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JLabel();
        txtHoraSaida = new javax.swing.JLabel();
        txtHoraEntrada = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtVeiculo = new javax.swing.JLabel();
        txtFuncionario = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JLabel();
        txtData = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Emitir comprovante");
        setResizable(false);
        getContentPane().setLayout(null);

        btnTelaHistorico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Historico teste.png"))); // NOI18N
        btnTelaHistorico.setToolTipText("Atalho para o histórico");
        btnTelaHistorico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTelaHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaHistoricoActionPerformed(evt);
            }
        });
        getContentPane().add(btnTelaHistorico);
        btnTelaHistorico.setBounds(200, 220, 74, 50);

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/imprimir.png"))); // NOI18N
        btnImprimir.setToolTipText("Imprimir comprovante");
        btnImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir);
        btnImprimir.setBounds(300, 220, 74, 50);

        txtValor.setBackground(new java.awt.Color(255, 255, 255));
        txtValor.setForeground(new java.awt.Color(255, 255, 255));
        txtValor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtValor);
        txtValor.setBounds(270, 120, 90, 20);

        txtDesconto.setBackground(new java.awt.Color(255, 255, 255));
        txtDesconto.setForeground(new java.awt.Color(255, 255, 255));
        txtDesconto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtDesconto);
        txtDesconto.setBounds(270, 70, 90, 20);

        txtHoraSaida.setBackground(new java.awt.Color(255, 255, 255));
        txtHoraSaida.setForeground(new java.awt.Color(255, 255, 255));
        txtHoraSaida.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtHoraSaida);
        txtHoraSaida.setBounds(150, 120, 90, 20);

        txtHoraEntrada.setBackground(new java.awt.Color(255, 255, 255));
        txtHoraEntrada.setForeground(new java.awt.Color(255, 255, 255));
        txtHoraEntrada.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtHoraEntrada);
        txtHoraEntrada.setBounds(30, 120, 90, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DESCONTO");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(270, 50, 80, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("VALOR");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(270, 100, 50, 20);

        txtVeiculo.setBackground(new java.awt.Color(255, 255, 255));
        txtVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        txtVeiculo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtVeiculo);
        txtVeiculo.setBounds(210, 170, 150, 20);

        txtFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        txtFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        txtFuncionario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtFuncionario);
        txtFuncionario.setBounds(30, 170, 160, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" SAÍDA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 100, 50, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ENTRADA");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 100, 60, 20);

        txtCodigo.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(30, 70, 90, 20);

        txtData.setBackground(new java.awt.Color(255, 255, 255));
        txtData.setForeground(new java.awt.Color(255, 255, 255));
        txtData.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtData);
        txtData.setBounds(150, 70, 90, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CÓDIGO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 50, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" DATA ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 50, 40, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FUNCIONÁRIO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 150, 100, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VEÍCULO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 150, 60, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("COMPROVANTE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 10, 140, 20);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Tela de Fundo Historico 02.jpg"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 0, 430, 310);

        setSize(new java.awt.Dimension(400, 309));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        if (txtCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "COMPROVANTE VAZIO!", "Atenção!", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "COMPROVANTE IMPRIMIDO COM SUCESSO!", "Mensagem", JOptionPane.CLOSED_OPTION);
        }

    }//GEN-LAST:event_btnImprimirActionPerformed

    FrmHistorico telaHistorico;

    private void btnTelaHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaHistoricoActionPerformed
        if (telaHistorico == null) {
            telaHistorico = new FrmHistorico();
            telaHistorico.setVisible(true);
        } else {
            telaHistorico.dispose();
            telaHistorico.setVisible(true);
            telaHistorico.setResizable(false);
        }
    }//GEN-LAST:event_btnTelaHistoricoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEmitirCupom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEmitirCupom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEmitirCupom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEmitirCupom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEmitirCupom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnTelaHistorico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel txtCodigo;
    private javax.swing.JLabel txtData;
    private javax.swing.JLabel txtDesconto;
    private javax.swing.JLabel txtFuncionario;
    private javax.swing.JLabel txtHoraEntrada;
    private javax.swing.JLabel txtHoraSaida;
    private javax.swing.JLabel txtValor;
    private javax.swing.JLabel txtVeiculo;
    // End of variables declaration//GEN-END:variables
}
